name: mg

channels:
- conda-forge
- metagraph/label/dev

dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black

# dependencies (so setup.py develop doesn't pip install them)
  - metagraph
  - metagraph-numba
